# tools_registry.py

from importlib import import_module
from typing import Callable, List, Dict, TypedDict, Union, Optional
from tax_calculators.tobacco_alcohol_tax import FIELD_LABELS as TA_FIELD_LABELS
TA_FIELD_LABELS_REG = {**TA_FIELD_LABELS, "budget_tax": "Tax cap (TWD)"}

class ToolMeta(TypedDict):
    name: str
    description: str
    module: str
    entry_func: Union[str, Dict[str, str]]
    keywords: List[str]
    required_fields: List[str]
    optimizable_fields: List[str]
    constraint_fields: List[str]
    field_labels: Dict[str, str]
    budget_field: str
    nl_parser: str

TOOLS: List[ToolMeta] = [
    {
        "name": "income_tax",
        "description": "Individual Income Tax",
        "module": "tax_calculators.income_tax",
        "entry_func": "calculate_comprehensive_income_tax",
        "keywords": ['Individual Income Tax', 'income'],
        "required_fields": [
            "is_married",
            "salary_self",
            "salary_spouse",
            "salary_dep",
            "interest_income",
            "stock_dividend",
            "house_transaction_gain",
            "other_income",
            "cnt_under_70",
            "cnt_over_70",
            "property_loss_deduction",
            "education_fee",
            "preschool_count",
            "long_term_care_count",
            "rent_deduction",
            "education_count",
            "disability_count",
            "itemized_deduction",
        ],
        "optimizable_fields": [
            "salary_self",
            "salary_spouse",
            "salary_dep",
            "interest_income",
            "stock_dividend",
            "house_transaction_gain",
            "other_income",
            "cnt_under_70",
            "cnt_over_70",
            "property_loss_deduction",
            "education_fee",
            "preschool_count",
            "long_term_care_count",
            "rent_deduction",
            "education_count",
            "disability_count",
            "itemized_deduction",
        ],
        "constraint_fields": ['free_vars', 'constraints'],
        "field_labels": {
            "is_married": "Are you married? (Yes/No)",
            "salary_self": "Your salary income (TWD)",
            "salary_spouse": "Spouse salary income (TWD)",
            "salary_dep": "Dependent salary income (TWD)",
            "interest_income": "Interest income (TWD)",
            "stock_dividend": "Stock dividend income (TWD)",
            "house_transaction_gain": "Real estate transaction gain (TWD)",
            "other_income": "Other income (TWD)",
            "cnt_under_70": "Number of dependents under age 70",
            "cnt_over_70": "Number of dependents age 70 and above",
            "property_loss_deduction": "Property loss deduction (TWD)",
            "education_fee": "Actual education expenses (TWD)",
            "preschool_count": "Number of preschool children",
            "long_term_care_count": "Count eligible for long-term care",
            "rent_deduction": "Housing rent expense (TWD)",
            "education_count": "Count eligible for education deduction",
            "disability_count": "Number of persons with disabilities",
            "itemized_deduction": "Itemized deductions amount (TWD)",
            "dividend_scheme_best": "Dividend taxation option",
            "tax_combined_progressive_with_dividend": "Combined method: Tax amount (progressive; incl. dividends)",
            "tax_combined_dividend_credit_raw": "Combined method: Dividend credit (dividends x 8.5%)",
            "tax_combined_dividend_credit_capped": "Combined method: Dividend credit (capped at 80,000)",
            "tax_combined_net": "Combined method: Net after credits",
            "tax_combined_tax_due": "Combined method: Tax payable",
            "tax_combined_refund": "Combined method: Refund",
            "tax_separate_progressive_without_dividend": "Separate method: Tax on other income (progressive; excl. dividends)",
            "tax_separate_dividend_tax_28": "Separate method: Dividend tax (dividends x 28%)",
            "tax_separate_net": "Separate method: Total tax due",
            "tax_separate_tax_due": "Separate method: Tax payable",
            "tax_separate_refund": "Separate method: Refund (usually 0)",
        },
        "alias": {
            "is_married": ['married', 'is married', 'marital status'],
            "salary_self": ['salary self', 'salary my'],
            "salary_spouse": ['salary spouse', 'salary partner'],
            "salary_dep": ['salary dep'],
            "interest_income": ['interest', 'interest income', 'deposit interest'],
            "stock_dividend": ['dividends', 'stock dividends', 'dividend income'],
            "house_transaction_gain": ['real estate gain', 'property sale gain', 'house sale gain'],
            "other_income": ['other income'],
            "cnt_under_70": ['count under 70', 'cnt under 70'],
            "cnt_over_70": ['count over 70', 'cnt over 70'],
            "property_loss_deduction": ['property loss deduction'],
            "education_fee": ['education fee'],
            "preschool_count": ['Number of preschool children'],
            "long_term_care_count": ['Count eligible for long-term care'],
            "rent_deduction": ['rent deduction', 'housing rent', 'rent expense'],
            "education_count": ['Count eligible for education deduction'],
            "disability_count": ['Number of persons with disabilities'],
            "itemized_deduction": ['itemized deduction']
        }
    },
    {
        "name": "foreigner_income_tax",
        "description": "Foreigner Individual Income Tax",
        "module": "tax_calculators.foreigner_income_tax",
        "entry_func": "calculate_foreigner_income_tax",
        "keywords": ['Foreigner Individual Income Tax', 'foreigner tax', 'non-resident'],
        "required_fields": [
            "days_of_stay",
            "is_departure",
            "is_married",
            "salary_self",
            "salary_spouse",
            "salary_dep",
            "interest_income",
            "interest_spouse",
            "interest_dep",
            "other_income",
            "other_income_spouse",
            "other_income_dep",
            "cnt_under_70",
            "cnt_over_70",
            "use_itemized",
            "itemized_deduction",
            "property_loss_deduction",
            "disability_count",
            "education_count",
            "education_fee",
            "preschool_count",
            "long_term_care_count",
            "rent_deduction",
        ],
        "optimizable_fields": [
            "days_of_stay",
            "salary_self",
            "salary_spouse",
            "salary_dep",
            "interest_income",
            "interest_spouse",
            "interest_dep",
            "other_income",
            "other_income_spouse",
            "other_income_dep",
            "cnt_under_70",
            "cnt_over_70",
            "use_itemized",
            "itemized_deduction",
            "property_loss_deduction",
            "disability_count",
            "education_count",
            "education_fee",
            "preschool_count",
            "long_term_care_count",
            "rent_deduction",
        ],
        "constraint_fields": ['free_vars', 'constraints'],
        "field_labels": {
            "days_of_stay": "Days stayed in Taiwan this year",
            "is_departure": "Departed Taiwan within the year? (Yes/No)",
            "is_married": "Are you married? (Yes/No)",
            "salary_self": "Your salary income (TWD)",
            "salary_spouse": "Spouse salary income (TWD)",
            "salary_dep": "Dependent salary income (TWD)",
            "interest_income": "Interest income (TWD)",
            "interest_spouse": "Spouse interest income (TWD)",
            "interest_dep": "Dependent interest income (TWD)",
            "other_income": "Other income (TWD)",
            "other_income_spouse": "Spouse other income (TWD)",
            "other_income_dep": "Dependent other income (TWD)",
            "cnt_under_70": "Number of dependents under age 70",
            "cnt_over_70": "Number of dependents age 70 and above",
            "use_itemized": "Use itemized deductions? (Yes/No)",
            "itemized_deduction": "Itemized deductions amount (TWD)",
            "property_loss_deduction": "Property loss deduction (TWD)",
            "disability_count": "Number of persons with disabilities",
            "education_count": "Count eligible for education deduction",
            "education_fee": "Actual education expenses (TWD)",
            "preschool_count": "Number of preschool children",
            "long_term_care_count": "Count eligible for long-term care",
            "rent_deduction": "Housing rent expense (TWD)",
        },
        "alias": {
            "days_of_stay": ['days of stay'],
            "is_departure": ['is departure'],
            "is_married": ['married', 'is married', 'marital status'],
            "salary_self": ['salary self', 'salary my'],
            "salary_spouse": ['salary spouse', 'salary partner'],
            "salary_dep": ['salary dep'],
            "interest_income": ['interest', 'interest income', 'deposit interest'],
            "interest_spouse": ['interest spouse'],
            "interest_dep": ['interest dep'],
            "other_income": ['other income'],
            "other_income_spouse": ['other income spouse'],
            "other_income_dep": ['other income dep'],
            "cnt_under_70": ['count under 70', 'cnt under 70'],
            "cnt_over_70": ['count over 70', 'cnt over 70'],
            "use_itemized": ['use itemized'],
            "itemized_deduction": ['itemized deduction'],
            "property_loss_deduction": ['property loss deduction'],
            "disability_count": ['Number of persons with disabilities'],
            "education_count": ['Count eligible for education deduction'],
            "education_fee": ['education fee'],
            "preschool_count": ['Number of preschool children'],
            "long_term_care_count": ['Count eligible for long-term care'],
            "rent_deduction": ['rent deduction', 'housing rent', 'rent expense']
        }
    },
    {
        "name": "business_income_tax",
        "description": "Business Income Tax",
        "module": "tax_calculators.business_income_tax",
        "entry_func": "calculate_business_income_tax",
        "keywords": ['Business Income Tax', 'corporate income tax', 'business tax'],
        "required_fields": [
            "OperatingRevenueTotal",
            "SalesReturn",
            "SalesAllowance",
            "OperatingCost",
            "OperatingExpensesLosses",
            "NonOperatingRevenueTotal",
            "NonOperatingLossExpenses",
            "Prev10LossDeduction",
            "TaxIncentiveExempt",
            "ExemptSecuritiesIncome",
            "ExemptLandIncome",
            "Article4_4HouseLandGain",
            "is_full_year",
            "m_partial",
        ],
        "optimizable_fields": [
            "OperatingRevenueTotal",
            "SalesReturn",
            "SalesAllowance",
            "OperatingCost",
            "OperatingExpensesLosses",
            "NonOperatingRevenueTotal",
            "NonOperatingLossExpenses",
            "Prev10LossDeduction",
            "TaxIncentiveExempt",
            "ExemptSecuritiesIncome",
            "ExemptLandIncome",
            "Article4_4HouseLandGain",
        ],
        "constraint_fields": ['free_vars', 'constraints'],
        "field_labels": {
            "OperatingRevenueTotal":   "Total operating revenue (TWD)",
            "SalesReturn":             "Sales returns (TWD)",
            "SalesAllowance":          "Sales allowances (TWD)",
            "OperatingCost":           "Cost of goods sold (TWD)",
            "OperatingExpensesLosses": "Operating expenses and losses (TWD)",
            "NonOperatingRevenueTotal":"Total non-operating income (TWD)",
            "NonOperatingLossExpenses":"Non-operating losses and expenses (TWD)",
            "Prev10LossDeduction":     "Loss carryforward (prior 10 years) (TWD)",
            "TaxIncentiveExempt":      "Tax incentive exemption (TWD)",
            "ExemptSecuritiesIncome":  "Exempt securities income (TWD)",
            "ExemptLandIncome":        "Exempt land income (TWD)",
            "Article4_4HouseLandGain": "Real estate transaction gain under Article 4-4 (TWD)",
            "is_full_year":            "Operate all year? (Yes/No)",
            "m_partial":               "Business months this year (1-12)",
        },
        "alias": {
            "OperatingRevenueTotal": ['OperatingRevenueTotal'],
            "SalesReturn": ['SalesReturn'],
            "SalesAllowance": ['SalesAllowance'],
            "OperatingCost": ['OperatingCost'],
            "OperatingExpensesLosses": ['OperatingExpensesLosses'],
            "NonOperatingRevenueTotal": ['NonOperatingRevenueTotal'],
            "NonOperatingLossExpenses": ['NonOperatingLossExpenses'],
            "Prev10LossDeduction": ['Prev10LossDeduction'],
            "TaxIncentiveExempt": ['TaxIncentiveExempt'],
            "ExemptSecuritiesIncome": ['ExemptSecuritiesIncome'],
            "ExemptLandIncome": ['ExemptLandIncome'],
            "Article4_4HouseLandGain": ['Article4 4HouseLandGain'],
            "is_full_year": ['is full year'],
            "m_partial": ['m partial']
        }
    },
    {
        "name": "cargo_tax",
        "description": "Commodity (Excise) Tax",
        "module": "tax_calculators.cargo_tax",
        "entry_func": { "minimize": "minimize_cargo_tax", "maximize": "maximize_cargo_qty" },
        "keywords": ['Commodity (Excise) Tax', 'excise', 'goods tax'],
        "required_fields": [
            "cement_white.quantity", "cement_portland_I.quantity", "cement_blast_furnace.quantity", "cement_other.quantity",
            "oil_gasoline.quantity", "oil_diesel.quantity", "oil_kerosene.quantity", "oil_jetfuel.quantity",
            "oil_fueloil.quantity", "oil_solvent.quantity", "lpg.quantity",
            "tire_bus_truck.assessed_price","tire_bus_truck.quantity",
            "tire_other.assessed_price","tire_other.quantity",
            "tire_inner_solid.assessed_price","tire_inner_solid.quantity",
            "drink_diluted_juice.assessed_price","drink_diluted_juice.quantity",
            "drink_other.assessed_price","drink_other.quantity",
            "drink_pure_juice.assessed_price","drink_pure_juice.quantity",
            "glass_plain.assessed_price","glass_plain.quantity",
            "glass_conductive_mold.assessed_price","glass_conductive_mold.quantity",
            "fridge.assessed_price","fridge.quantity",
            "tv.assessed_price","tv.quantity",
            "hvac_central.assessed_price","hvac_central.quantity",
            "hvac_non_central.assessed_price","hvac_non_central.quantity",
            "dehumidifier.assessed_price","dehumidifier.quantity",
            "vcr.assessed_price","vcr.quantity",
            "recorder.assessed_price","recorder.quantity",
            "stereo.assessed_price","stereo.quantity",
            "oven.assessed_price","oven.quantity",
            "car_le_2000cc.assessed_price","car_le_2000cc.quantity",
            "car_gt_2000cc.assessed_price","car_gt_2000cc.quantity",
            "truck_bus.assessed_price","truck_bus.quantity",
            "motorcycle.assessed_price","motorcycle.quantity"
        ],
        "optimizable_fields": [
            "cement_white.quantity", "cement_portland_I.quantity", "cement_blast_furnace.quantity", "cement_other.quantity",
            "oil_gasoline.quantity", "oil_diesel.quantity", "oil_kerosene.quantity", "oil_jetfuel.quantity",
            "oil_fueloil.quantity", "oil_solvent.quantity", "lpg.quantity",
            "tire_bus_truck.assessed_price","tire_bus_truck.quantity",
            "tire_other.assessed_price","tire_other.quantity",
            "tire_inner_solid.assessed_price","tire_inner_solid.quantity",
            "drink_diluted_juice.assessed_price","drink_diluted_juice.quantity",
            "drink_other.assessed_price","drink_other.quantity",
            "drink_pure_juice.assessed_price","drink_pure_juice.quantity",
            "glass_plain.assessed_price","glass_plain.quantity",
            "glass_conductive_mold.assessed_price","glass_conductive_mold.quantity",
            "fridge.assessed_price","fridge.quantity",
            "tv.assessed_price","tv.quantity",
            "hvac_central.assessed_price","hvac_central.quantity",
            "hvac_non_central.assessed_price","hvac_non_central.quantity",
            "dehumidifier.assessed_price","dehumidifier.quantity",
            "vcr.assessed_price","vcr.quantity",
            "recorder.assessed_price","recorder.quantity",
            "stereo.assessed_price","stereo.quantity",
            "oven.assessed_price","oven.quantity",
            "car_le_2000cc.assessed_price","car_le_2000cc.quantity",
            "car_gt_2000cc.assessed_price","car_gt_2000cc.quantity",
            "truck_bus.assessed_price","truck_bus.quantity",
            "motorcycle.assessed_price","motorcycle.quantity"
        ],
        "constraint_fields": ['free_vars', 'constraints', 'budget_tax'],
        "budget_field": "budget_tax",
        "nl_parser": "agents.parsers.cargo_nl_parser:nl_to_payload",
        "report_renderer": "agents.report_renderer:render_report",
        "field_labels": {
            "budget_tax": "Tax cap (TWD)",
            "cement_white.quantity": "White cement - Quantity",
            "cement_portland_I.quantity": "Portland cement (Type I) - Quantity",
            "cement_blast_furnace.quantity": "Portland blast-furnace cement - Quantity",
            "cement_other.quantity": "Cement substitutes & others - Quantity",
            "oil_gasoline.quantity": "Gasoline - Quantity",
            "oil_diesel.quantity": "Diesel - Quantity",
            "oil_kerosene.quantity": "Kerosene - Quantity",
            "oil_jetfuel.quantity": "Aviation fuel - Quantity",
            "oil_fueloil.quantity": "Fuel oil - Quantity",
            "oil_solvent.quantity": "Solvent oil - Quantity",
            "lpg.quantity": "Liquefied petroleum gas (LPG) - Quantity",
            "tire_bus_truck.assessed_price": "Tires for large buses/trucks - Taxable price per unit (TWD)",
            "tire_bus_truck.quantity": "Tires for large buses/trucks - Quantity",
            "tire_other.assessed_price": "Other rubber tires - Taxable price per unit (TWD)",
            "tire_other.quantity": "Other rubber tires - Quantity",
            "tire_inner_solid.assessed_price": "Inner / solid tires, etc. - Taxable price per unit (TWD)",
            "tire_inner_solid.quantity": "Inner / solid tires, etc. - Quantity",
            "drink_diluted_juice.assessed_price": "Diluted natural fruit/vegetable juice - Taxable price per unit (TWD)",
            "drink_diluted_juice.quantity": "Diluted natural fruit/vegetable juice - Quantity",
            "drink_other.assessed_price": "Other beverages - Taxable price per unit (TWD)",
            "drink_other.quantity": "Other beverages - Quantity",
            "drink_pure_juice.assessed_price": "Natural fruit juice - Taxable price per unit (TWD)",
            "drink_pure_juice.quantity": "Natural fruit juice - Quantity",
            "glass_plain.assessed_price": "Standard flat glass - Taxable price per unit (TWD)",
            "glass_plain.quantity": "Standard flat glass - Quantity",
            "glass_conductive_mold.assessed_price": "Conductive / mold glass - Taxable price per unit (TWD)",
            "glass_conductive_mold.quantity": "Conductive / mold glass - Quantity",
            "fridge.assessed_price": "Refrigerator - Taxable price per unit (TWD)",
            "fridge.quantity": "Refrigerator - Quantity",
            "tv.assessed_price": "Color TV - Taxable price per unit (TWD)",
            "tv.quantity": "Color TV - Quantity",
            "hvac_central.assessed_price": "Central air conditioning - Taxable price per unit (TWD)",
            "hvac_central.quantity": "Central air conditioning - Quantity",
            "hvac_non_central.assessed_price": "Non-central air conditioning - Taxable price per unit (TWD)",
            "hvac_non_central.quantity": "Non-central air conditioning - Quantity",
            "dehumidifier.assessed_price": "Dehumidifier - Taxable price per unit (TWD)",
            "dehumidifier.quantity": "Dehumidifier - Quantity",
            "vcr.assessed_price": "Video recorder - Taxable price per unit (TWD)",
            "vcr.quantity": "Video recorder - Quantity",
            "recorder.assessed_price": "Audio recorder - Taxable price per unit (TWD)",
            "recorder.quantity": "Audio recorder - Quantity",
            "stereo.assessed_price": "Audio system - Taxable price per unit (TWD)",
            "stereo.quantity": "Audio system - Quantity",
            "oven.assessed_price": "Electric oven - Taxable price per unit (TWD)",
            "oven.quantity": "Electric oven - Quantity",
            "car_le_2000cc.assessed_price": "Passenger car <=2000cc - Taxable price per unit (TWD)",
            "car_le_2000cc.quantity": "Passenger car <=2000cc - Quantity",
            "car_gt_2000cc.assessed_price": "Passenger car >2000cc - Taxable price per unit (TWD)",
            "car_gt_2000cc.quantity": "Passenger car >2000cc - Quantity",
            "truck_bus.assessed_price": "Trucks / large buses, etc. - Taxable price per unit (TWD)",
            "truck_bus.quantity": "Trucks / large buses, etc. - Quantity",
            "motorcycle.assessed_price": "Motorcycle - Taxable price per unit (TWD)",
            "motorcycle.quantity": "Motorcycle - Quantity"
        },
        "alias": {
            "free_vars": ['free vars'],
            "constraints": ['constraints'],
            "budget_tax": ['Tax cap'],
            "quantity": ['quantity'],
            "assessed_price": ['assessed price']
        }
    },
    {
        "name": "vat_tax",
        "description": "Value-Added Business Tax (VAT)",
        "module": "tax_calculators.sale_tax",
        "entry_func": "minimize_vat_tax",
        "keywords": ['Value-Added Business Tax (VAT)', 'VAT'],
        "required_fields": ['output_tax_amt', 'input_tax_amt'],
        "optimizable_fields": ['output_tax_amt', 'input_tax_amt'],
        "constraint_fields": ['free_vars', 'constraints'],
        "nl_parser": "agents.parsers.vat_nl_parser_simple:nl_to_payload",
        "field_labels": {
            "output_tax_amt": "Output tax base (tax base before tax, TWD)",
            "input_tax_amt":  "Input tax base (tax base before tax, TWD)",
            "free_vars": "Variables to relax (comma-separated): output_tax_amt, input_tax_amt.",
            "constraints": "Available variables: output_tax_amt, input_tax_amt, out5, in5, total_vat."
        },
        "alias": {
            "output_tax_amt": ['output tax amt'],
            "input_tax_amt": ['input tax amt'],
            "free_vars": ['free vars'],
            "constraints": ['constraints']
        }
    },
    {
        "name": "nvat_tax",
        "description": "Non-VAT Business Tax",
        "module": "tax_calculators.sale_tax",
        "entry_func": { "minimize": "minimize_nvat_tax", "maximize": "maximize_nvat_under_budget" },
        "keywords": ['Non-VAT Business Tax', 'nVAT'],
        "required_fields": ['cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8'],
        "optimizable_fields": ['cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8'],
        "constraint_fields": ['free_vars', 'constraints', 'budget_tax'],
        "budget_field": "budget_tax",
        "nl_parser": "agents.parsers.nvat_nl_parser:nl_to_payload",
        "field_labels": {
            "cat1": "Small-scale business operator (sales amount, TWD)",
            "cat2": "Reinsurance premium income (sales amount, TWD)",
            "cat3": "Financial sector (exclusive main business) (sales amount, TWD)",
            "cat4": "Banking/Insurance main business (sales amount, TWD)",
            "cat5": "Financial sector (non-exclusive main business) (sales amount, TWD)",
            "cat6": "Night club (sales amount, TWD)",
            "cat7": "Bars/hostess clubs, etc. (sales amount, TWD)",
            "cat8": "Agricultural products wholesale market (sales amount, TWD)",
            "budget_tax": "Tax cap (TWD)",
            "free_vars": "Variables to relax (comma-separated): cat1..cat8.",
            "constraints": "Constraints (JSON/text). Can span categories, e.g., {\"cat7\":{\">=\":\"cat6*1.2\"}}. You may use total_tax.",
        },
        "alias": {
            "cat1": ['cat1'],
            "cat2": ['cat2'],
            "cat3": ['cat3'],
            "cat4": ['cat4'],
            "cat5": ['cat5'],
            "cat6": ['cat6'],
            "cat7": ['cat7'],
            "cat8": ['cat8'],
            "budget_tax": ['Tax cap'],
            "free_vars": ['free vars'],
            "constraints": ['constraints']
        }
    },
    {
        "name": "ta_tax",
        "description": "Tobacco and Alcohol Tax",
        "module": "tax_calculators.tobacco_alcohol_tax",
        "entry_func": {
            "minimize": "minimize_ta_tax",
            "maximize": "maximize_ta_qty",
        },
        "keywords": ['Tobacco and Alcohol Tax', 'tobacco', 'alcohol', 'ABV'],
        "required_fields": [
            "cigarettes_new.quantity",
            "tobacco_cut_new.quantity",
            "cigar_new.quantity",
            "tobacco_other_new.quantity",
            "cigarettes_old.quantity",
            "tobacco_cut_old.quantity",
            "cigar_old.quantity",
            "tobacco_other_old.quantity",

            "beer.quantity",
            "brew_other.quantity",
            "distilled.quantity",
            "reprocessed_gt20.quantity",
            "reprocessed_le20.quantity",
            "cooking_wine.quantity",
            "cooking_wine_old.quantity",
            "alcohol_other.quantity",
            "ethanol.quantity",
            "ethanol_old.quantity",

            "brew_other.alcohol_content",
            "distilled.alcohol_content",
            "reprocessed_le20.alcohol_content",
            "alcohol_other.alcohol_content",
        ],
        "optimizable_fields": [
            "cigarettes_new.quantity",
            "tobacco_cut_new.quantity",
            "cigar_new.quantity",
            "tobacco_other_new.quantity",
            "cigarettes_old.quantity",
            "tobacco_cut_old.quantity",
            "cigar_old.quantity",
            "tobacco_other_old.quantity",

            "beer.quantity",
            "brew_other.quantity",
            "distilled.quantity",
            "reprocessed_gt20.quantity",
            "reprocessed_le20.quantity",
            "cooking_wine.quantity",
            "cooking_wine_old.quantity",
            "alcohol_other.quantity",
            "ethanol.quantity",
            "ethanol_old.quantity",

            "brew_other.alcohol_content",
            "distilled.alcohol_content",
            "reprocessed_le20.alcohol_content",
            "alcohol_other.alcohol_content",
        ],
        "constraint_fields": ['free_vars', 'constraints', 'budget_tax'],
        "budget_field": "budget_tax",
        "nl_parser": "agents.parsers.ta_nl_parser:nl_to_payload",
        "field_labels":TA_FIELD_LABELS_REG,
        "alias": {
            "free_vars": ['free vars'],
            "constraints": ['constraints'],
            "budget_tax": ['Tax cap'],
            "quantity": ['quantity'],
            "alcohol_content": ['ABV']
        },
        "row_fields": ['quantity', 'alcohol_content'],
        "report_renderer": "agents.report_renderer:render_report",
    },
    {
        "name": "estate_tax",
        "description": "Estate Tax",
        "module": "tax_calculators.estate_tax",
        "entry_func": "calculate_estate_tax",
        "keywords": ['Estate Tax', 'estate tax'],
        "required_fields": [
            "death_period",
            "is_military_police",
            "land_value",
            "building_value",
            "house_value",
            "deposit_bonds_value",
            "stock_invest_value",
            "cash_gold_jewelry_value",
            "gift_in_2yrs_value",
            "spouse_count",
            "lineal_descendant_count",
            "father_mother_count",
            "disability_count",
            "dependent_count",
            "farmland_val",
            "inheritance_6to9_val",
            "unpaid_tax_fines_val",
            "unpaid_debts_val",
            "will_management_fee",
            "public_facility_retention_val",
            "spouse_surplus_right_val",
            "gift_tax_offset",
            "foreign_tax_offset",
        ],
        "optimizable_fields": [
            "land_value",
            "building_value",
            "house_value",
            "deposit_bonds_value",
            "stock_invest_value",
            "cash_gold_jewelry_value",
            "gift_in_2yrs_value",
            "spouse_count",
            "lineal_descendant_count",
            "father_mother_count",
            "disability_count",
            "dependent_count",
            "farmland_val",
            "inheritance_6to9_val",
            "unpaid_tax_fines_val",
            "unpaid_debts_val",
            "will_management_fee",
            "public_facility_retention_val",
            "spouse_surplus_right_val",
            "gift_tax_offset",
            "foreign_tax_offset",
        ],
        "constraint_fields": ['free_vars', 'constraints'],
        "field_labels": {
            "death_period": (
                "Decedent's date of death (ROC year/month/day, e.g., 113/3/15 or 112)""; or enter a period code 1-5:\n""  1. 103/01/01 - 106/05/11\n""  2. 106/05/12 - 110/12/31\n""  3. 111/01/01 - 112/12/31\n""  4. 113/01/01 - 113/12/31\n""  5. 114/01/01 and after"
            ),
            "is_military_police":      "Died in the line of duty? (Yes/No)",
            "land_value":              "Land value (TWD)",
            "building_value":          "Buildings/structures value (TWD)",
            "house_value":             "House value (TWD)",
            "deposit_bonds_value":     "Deposits / claims value (TWD)",
            "stock_invest_value":      "Stocks / investments value (TWD)",
            "cash_gold_jewelry_value": "Cash / jewelry value (TWD)",
            "gift_in_2yrs_value":      "Gifts within 2 years before death (TWD)",
            "spouse_count":            "Number of spouses",
            "lineal_descendant_count": "Number of lineal descendants",
            "father_mother_count":     "Number of parents",
            "disability_count":        "Number of persons with disabilities",
            "dependent_count":         "Number of other dependents",
            "farmland_val":            "Agricultural land value (TWD)",
            "inheritance_6to9_val":    "Agricultural deduction (years 6-9) (TWD)",
            "unpaid_tax_fines_val":    "Unpaid taxes/fines (TWD)",
            "unpaid_debts_val":        "Unpaid debts (TWD)",
            "will_management_fee":     "Will administration fee (TWD)",
            "public_facility_retention_val": "Public facility reservation value (TWD)",
            "spouse_surplus_right_val": "Spousal residual property rights value (TWD)",
            "gift_tax_offset":         "Gift tax credit (TWD)",
            "foreign_tax_offset":      "Foreign tax credit (TWD)",
            "free_vars":               "Free variables to relax (comma-separated)",
            "variable_constraints":    "Variable constraints (JSON/text; leave blank if none)",
        },
        "alias": {
            "death_period": ['death period'],
            "is_military_police": ['is military police'],
            "land_value": ['land value'],
            "building_value": ['building value'],
            "house_value": ['house value'],
            "deposit_bonds_value": ['deposit bonds value'],
            "stock_invest_value": ['stock invest value'],
            "cash_gold_jewelry_value": ['cash gold jewelry value'],
            "gift_in_2yrs_value": ['gift in 2yrs value'],
            "spouse_count": ['Number of spouses'],
            "lineal_descendant_count": ['Number of lineal descendants'],
            "father_mother_count": ['Number of parents'],
            "disability_count": ['Number of persons with disabilities'],
            "dependent_count": ['Number of other dependents'],
            "farmland_val": ['farmland val'],
            "inheritance_6to9_val": ['inheritance 6to9 val'],
            "unpaid_tax_fines_val": ['unpaid tax fines val'],
            "unpaid_debts_val": ['unpaid debts val'],
            "will_management_fee": ['will management fee'],
            "public_facility_retention_val": ['public facility retention val'],
            "spouse_surplus_right_val": ['spouse surplus right val'],
            "gift_tax_offset": ['gift tax offset'],
            "foreign_tax_offset": ['foreign tax offset'],
            "free_vars": ['free vars'],
            "constraints": ['constraints']
        },
    },
    {
        "name": "gift_tax",
        "description": "Gift Tax",
        "module": "tax_calculators.gift_tax",
        "entry_func": "calculate_gift_tax",
        "keywords": ['Gift Tax', 'gift tax'],
        "required_fields": [
            "period_choice",
            "land_value",
            "ground_value",
            "house_value",
            "others_value",
            "not_included_land",
            "not_included_house",
            "not_included_others",
            "remaining_exemption_98",
            "previous_gift_sum_in_this_year",
            "land_increment_tax",
            "deed_tax",
            "other_gift_burdens",
            "previous_gift_tax_or_credit",
            "new_old_system_adjustment",
        ],
        "optimizable_fields": [
            "land_value",
            "ground_value",
            "house_value",
            "others_value",
            "not_included_land",
            "not_included_house",
            "not_included_others",
            "remaining_exemption_98",
            "previous_gift_sum_in_this_year",
            "land_increment_tax",
            "deed_tax",
            "other_gift_burdens",
            "previous_gift_tax_or_credit",
            "new_old_system_adjustment",
        ],
        "constraint_fields": ['free_vars', 'constraints'],
        "field_labels": {
            "period_choice": (
                "Gift year (ROC year, e.g., 112), or enter a period code 1-4:\n""  1. 98/01/23 - 106/05/11\n""  2. 106/05/12 - 110/12/31\n""  3. 111/01/01 - 113/12/31\n""  4. 114/01/01 and after"
            ),
            "land_value": "Land value (TWD)",
            "ground_value": "Buildings/structures value (TWD)",
            "house_value": "House value (TWD)",
            "others_value": "Movable property & rights value (TWD)",
            "not_included_land": "Excluded land (TWD)",
            "not_included_house": "Excluded house (TWD)",
            "not_included_others": "Excluded others (TWD)",
            "remaining_exemption_98": "Remaining exemption (ROC 98, old system) (TWD)",
            "previous_gift_sum_in_this_year": "Prior gifts in the same year (total) (TWD)",
            "land_increment_tax": "Land value increment tax (TWD)",
            "deed_tax": "Deed tax (TWD)",
            "other_gift_burdens": "Other gift burdens (TWD)",
            "previous_gift_tax_or_credit": "Previous gift tax / credit (TWD)",
            "new_old_system_adjustment": "New/old system adjustment (TWD; can be negative)",
            "free_vars": "Free variables to relax (comma-separated)",
            "variable_constraints": "Variable constraints (JSON/text; leave blank if none)",
        },
        "alias": {
            "period_choice": ['Gift year'],
            "land_value": ['land value'],
            "ground_value": ['ground value'],
            "house_value": ['house value'],
            "others_value": ['others value'],
            "not_included_land": ['not included land'],
            "not_included_house": ['not included house'],
            "not_included_others": ['not included others'],
            "remaining_exemption_98": ['remaining exemption 98'],
            "previous_gift_sum_in_this_year": ['previous gift sum in this year'],
            "land_increment_tax": ['land increment tax'],
            "deed_tax": ['deed tax'],
            "other_gift_burdens": ['other gift burdens'],
            "previous_gift_tax_or_credit": ['previous gift tax or credit'],
            "new_old_system_adjustment": ['new old system adjustment'],
            "free_vars": ['free vars'],
            "constraints": ['constraints']
        },
    },
    {
        "name": "securities_tx_tax",
        "description": "Securities Transaction Tax",
        "module": "tax_calculators.securities_and_futures_transaction_tax",
        "entry_func": "compute_securities_transaction_tax",
        "keywords": ['Securities Transaction Tax'],
        "required_fields": [
                "stock.tp",
                "bond.tp",
                "warrant.tp",
                "warrant_delivery_stock.ep",
                "warrant_delivery_stock.sc",
                "warrant_delivery_cash.ep",
                "warrant_delivery_cash.sc",
            ],
        "optimizable_fields": [
                "stock.tp",
                "bond.tp",
                "warrant.tp",
                "warrant_delivery_stock.ep",
                "warrant_delivery_stock.sc",
                "warrant_delivery_cash.ep",
                "warrant_delivery_cash.sc",
            ],              
        "constraint_fields": ['free_vars', 'constraints', 'target_tax'],
        "budget_field": "target_tax",
        "nl_parser": "agents.parsers.securities_nl_parser:nl_to_payload",
        "field_labels": {
                **__import__("tax_calculators.securities_and_futures_transaction_tax",
                            fromlist=["SEC_FIELD_LABELS"]).SEC_FIELD_LABELS,
                "target_tax": "Tax cap"
            },                
        "report_renderer": "agents.report_renderer:render_report",
        "row_fields": ['tp', 'ep', 'sc'],
        "alias": {
            "free_vars": ['free vars'],
            "constraints": ['constraints'],
            "target_tax": ['Tax cap'],
            "tp": ['tp'],
            "ep": ['ep'],
            "sc": ['sc']
        },
    },
    {
        "name": "futures_tx_tax",
        "description": "Futures Transaction Tax",
        "module": "tax_calculators.securities_and_futures_transaction_tax",
        "entry_func": "compute_futures_transaction_tax",
        "keywords": ['Futures Transaction Tax'],
        "required_fields": [
            "stock_index.ca",
            "interest_rate_30.ca",
            "interest_rate_10.ca",
            "gold.ca",
            "option.pa",
            "option.ca",
        ],   
        "optimizable_fields": [
            "stock_index.ca",
            "interest_rate_30.ca",
            "interest_rate_10.ca",
            "gold.ca",
            "option.pa",
            "option.ca",
        ],                       
        "constraint_fields": ['free_vars', 'constraints', 'target_tax'],
        "budget_field": "target_tax",
        "nl_parser": "agents.parsers.futures_nl_parser:nl_to_payload",
        "field_labels": {
            **__import__("tax_calculators.securities_and_futures_transaction_tax",
                        fromlist=["FUT_FIELD_LABELS"]).FUT_FIELD_LABELS,
            "target_tax": "Tax cap"
        },                
        "row_fields": ['ca', 'pa'],
        "report_renderer": "agents.report_renderer:render_report",
        "alias": {
            "free_vars": ['free vars'],
            "constraints": ['constraints'],
            "target_tax": ['Tax cap'],
            "ca": ['ca'],
            "pa": ['premium']
        },
    },
    {
        "name": "special_goods_tax",
        "description": "Special Goods Tax",
        "module": "tax_calculators.special_tax",
        "entry_func": {
            "minimize": "minimize_sg_tax",
            "maximize": "maximize_qty_under_budget_sg"
        },
        "keywords": ['Special Goods Tax'],
        "required_fields": [
            "car.price",
            "car.quantity",
            "yacht.price",
            "yacht.quantity",
            "aircraft.price",
            "aircraft.quantity",
            "coral_ivory.price",
            "coral_ivory.quantity",
            "furniture.price",
            "furniture.quantity"
        ],
        "optimizable_fields": [
            "car.price",
            "car.quantity",
            "yacht.price",
            "yacht.quantity",
            "aircraft.price",
            "aircraft.quantity",
            "coral_ivory.price",
            "coral_ivory.quantity",
            "furniture.price",
            "furniture.quantity"
        ],
        "constraint_fields": ['free_vars', 'constraints', 'budget_tax'],
        "budget_field": "budget_tax",
        "nl_parser": "agents.parsers.special_goods_nl_parser:nl_to_payload_fixed",
        "field_labels": {
            "budget_tax": "Tax cap (TWD)",
            "car.price": "Passenger car: Unit price (TWD)",
            "car.quantity": "Passenger car: Quantity",
            "yacht.price": "Yacht: Unit price (TWD)",
            "yacht.quantity": "Yacht: Quantity",
            "aircraft.price": "Aircraft/Helicopter: Unit price (TWD)",
            "aircraft.quantity": "Aircraft/Helicopter: Quantity",
            "coral_ivory.price": "Coral/Ivory, etc.: Unit price (TWD)",
            "coral_ivory.quantity": "Coral/Ivory, etc.: Quantity",
            "furniture.price": "Furniture: Unit price (TWD)",
            "furniture.quantity": "Furniture: Quantity"
        },
        "report_renderer": "agents.report_renderer:render_report",
        "alias": {
            "free_vars": ['free vars'],
            "constraints": ['constraints'],
            "budget_tax": ['Tax cap'],
            "car.price": ['car.price'],
            "car.quantity": ['car.quantity'],
            "yacht.price": ['yacht.price'],
            "yacht.quantity": ['yacht.quantity'],
            "aircraft.price": ['aircraft.price'],
            "aircraft.quantity": ['aircraft.quantity'],
            "coral_ivory.price": ['coral ivory.price'],
            "coral_ivory.quantity": ['coral ivory.quantity'],
            "furniture.price": ['furniture.price'],
            "furniture.quantity": ['furniture.quantity']
        },
    },
    {
        "name": "special_tax",
        "description": "Special Services Tax",
        "module": "tax_calculators.special_tax",
        "entry_func": "minimize_special_services_tax",
        "keywords": ['Special Services Tax'],
        "required_fields": ['sales_price'],
        "optimizable_fields": ['sales_price'],
        "constraint_fields": ['free_vars', 'constraints'],
        "field_labels": {
            "sales_price": "High-value consumption service membership rights sales (TWD)",
            "free_vars": "Free variables to relax (comma-separated)",
            "constraints": "Variable constraints (JSON/text; leave blank if none)",
        },
        "alias": {
            "sales_price": ['sales price'],
            "free_vars": ['free vars'],
            "constraints": ['constraints']
        },
    }
]

def get_tool(name: str) -> Callable[[dict], dict]:
    """
    entry_func  dict resolve_entry_func(name, op)
    """
    meta = next(t for t in TOOLS if t["name"] == name)
    entry = meta["entry_func"]
    if isinstance(entry, str):
        return getattr(import_module(meta["module"]), entry)
    raise ValueError(f"Tool '{name}' has multiple entry functions; use resolve_entry_func(name, op).")

def resolve_entry_func(name: str, op: Optional[str] = None) -> Callable[[dict], dict]:
    """
    op  'minimize'  'maximize' key
     entry_func 
    """
    meta = next(t for t in TOOLS if t["name"] == name)
    entry = meta["entry_func"]
    mod = import_module(meta["module"])
    if isinstance(entry, dict):
        if not op:
            raise ValueError(f"Tool '{name}' requires an 'op' to select entry function.")
        fn = entry.get(op)
        if not fn:
            raise ValueError(f"Tool '{name}' has no entry for op='{op}'.")
        return getattr(mod, fn)
    return getattr(mod, entry)